DEVICE_PATH := device/brcm/rpi3

TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := true

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi

# Board
TARGET_BOARD_PLATFORM := bcm2710

# Kernel
TARGET_KERNEL_CONFIG := lineageos_rpi3_defconfig
BOARD_KERNEL_IMAGE_NAME := zImage
BOARD_KERNEL_PAGESIZE := 2048
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_SOURCE := kernel/brcm/rpi3

# Audio
USE_XML_AUDIO_POLICY_CONF := 1

# Camera
USE_CAMERA_STUB := true

# Graphics
BOARD_GPU_DRIVERS := vc4
BOARD_USE_BGRA_8888 := true
TARGET_USE_PAN_DISPLAY := true
USE_OPENGL_RENDERER := true
TARGET_USES_HWC2 := true

# HIDL
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/manifest.xml

# Partitions
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912 # 512M
BOARD_USERDATAIMAGE_PARTITION_SIZE := 134217728 # 128M
BOARD_FLASH_BLOCK_SIZE := 4096

# SELinux
BOARD_SEPOLICY_DIRS := $(DEVICE_PATH)/sepolicy

# Wifi
BOARD_WLAN_DEVICE := bcmdhd
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_bcmdhd
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
